### ISSUE TITLE
Sistema centralizado de Raspis para Cadena de Heladerias

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DELVIENTO#1]
@mkreyness necesito que empieces a investigar cómo armar este sistema mientras hago aprobar las estéticas. Te paso todos los datos en formato ficha técnica para que sea más claro. Cualquier duda me avisás. La armamos con MS.

CLIENTE: Del viento (helados)

QUÉ TIENE HOY: Tiene un sistema local de 3 televisores en cada sucursal en los que muestra los gustos que tiene disponibles.  

QUÉ QUIERE: Un sistema centralizado para modificar los gustos cuando se le van acabando tanto desde el local como desde un monitoreo central de todas. El menú es un video, porque tiene un logito o fondo animado, pero el resto es estático.

PROBLEMA: Hoy cada vez que tiene que cambiar un video porque se terminó un gusto tiene un quilombo. Tiene que cargar o descargar un video del servidor. Además, como es un servidor local, cuando se corta la luz tiene un problema.

QUÉ NECESITA: Centralizar en un sistema todo y que desde un CMS en una computadora los empleados puedan gestionar los cambios en los videos.

Queremos armar un sistema con 3 televisores comunes por local con una raspi en cada uno. Cada raspi está en una red interna con servidor interno en cada heladería, pero a ese servidor interno se puede acceder desde la red local o desde afuera por internet. Es importante el servidor local para que guarde la data por más que no haya internet.

QUÉ HAY QUE PROGRAMAR?

3 pantallas que despliegan 12 gustos máximo cada pantalla. El tiempo que está ese video es en loop. Hay que hacer un cms que actualice directamente los gustos modificando los videos.

La lista total es de 50 sabores, pero se mostrarían siempre 36. El sistema tiene que armar los compilados de video en función de los datos que ingresar el responsable del local: qué gustos quedaron y qué gusto no quedan más.

PARÁMETROS:
1. Gustos
2. Cantidad de gustos por monitor.
3. Grupos= A su vez los sabores se agrupan en: Cremosos, frutales, etc, que no deben quedar separados en distintos monitores.
4. Video de gustos= le llamamos así a una imagen que tiene 12 gustos. Parece una gráfica pero tiene una pequeña animación inserta. El resto es un listados de nombres estático como cualquier menú.
5. Videos promocionales= vídeos que se intercalan con los vídeos de los gustos.

FORMA DEL SISTEMA:

Hay una Base master de todos los servidores locales y bases esclavas, que solo tienen gestión local.

El sistema ordena de acuerdo a los gustos y que cada grupo quede siempre entero en una pantalla, no repartido en varias. 

NIVELES DE ACCESO: SON DOS
1. Administrador central: Define qué sabores existen en la base, selecciona vídeos promocionales y carga nuevos y para qué local se habilitan, monitorea todos los servidores locales.
2. Responsable del local: Solo selecciona cuales gustos hay y cuales no tildando casilleros, y luego clickea en el botón de "enviar" para actualizar las pantallas.

FUNCIONAMIENTO

Cada monitor tiene un número único (y raspi única) dentro de todo el sistema, secuenciado en todas las heladeras, Ej: Heladeria 1 tiene monitores 1, 2 y 3. Heladería 2 tiene monitores 4, 5 y 6, etc.

En el CMS hay un pop up de gustos ya preparados. El tipo selecciona pantalla 1 y aparece un pop up con 50 gustos totales. El empleado selecciona 12 gustos que aparecerán en esa pantalla. Para cambiar la segunda pantalla entrás a la segunda pantalla y selecciona otros 12 gustos. 

QUÉ HAY QUE COTIZAR:

Horas que te llevaría diseñar el sistema, armar cms bien amigable (más amigable estéticamente que el que tenemos, habría que hablarlo con Fede) para seleccionar qué video va en cada pantalla, con usuarios y niveles de acceso, para que alguien pueda hacerlo desde la central o de cada una de las sucursales.

Incluí las horas que te lleve estudiar como hacemos el display, si pusheando el video a los magicinfo o poniendo una raspi en cada monitor

Aparte nosotros haríamos el diseño y animación de los cartelitos individuales.

QUÉ APORTÓ MS:

MS encontró una plataforma open source, con el que armó un video 12 videos individuales todo por comand line:

/ffmpeg -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -i ddl640.avi -filter_complex "
        nullsrc=size=1280x720 [base];
        [0:v] setpts=PTS-STARTPTS, scale=640x120 [A1];
        [1:v] setpts=PTS-STARTPTS, scale=640x120 [B1];
        [2:v] setpts=PTS-STARTPTS, scale=640x120 [A2];
        [3:v] setpts=PTS-STARTPTS, scale=640x120 [B2];
        [4:v] setpts=PTS-STARTPTS, scale=640x120 [A3];
        [5:v] setpts=PTS-STARTPTS, scale=640x120 [B3];
        [6:v] setpts=PTS-STARTPTS, scale=640x120 [A4];
        [7:v] setpts=PTS-STARTPTS, scale=640x120 [B4];
        [8:v] setpts=PTS-STARTPTS, scale=640x120 [A5];
        [9:v] setpts=PTS-STARTPTS, scale=640x120 [B5];
        [10:v] setpts=PTS-STARTPTS, scale=640x120 [A6];
        [11:v] setpts=PTS-STARTPTS, scale=640x120 [B6];
        [base][A1] overlay=shortest=1 [tmp1];
        [tmp1][B1] overlay=shortest=1:x=640 [tmp2];
        [tmp2][A2] overlay=shortest=1:y=120 [tmp3];
        [tmp3][B2] overlay=shortest=1:x=640:y=120 [tmp4];
        [tmp4][A3] overlay=shortest=1:x=0:y=240 [tmp5];
        [tmp5][B3] overlay=shortest=1:x=640:y=240 [tmp6];
        [tmp6][A4] overlay=shortest=1:x=0:y=360 [tmp7];
        [tmp7][B4] overlay=shortest=1:x=640:y=360 [tmp8];
        [tmp8][A5] overlay=shortest=1:x=0:y=480 [tmp9];
        [tmp9][B5] overlay=shortest=1:x=640:y=480 [tmp10];
        [tmp10][A6] overlay=shortest=1:x=0:y=600 [tmp11];
        [tmp11][B6] overlay=shortest=1:x=640:y=600
    " -c:v libx264 output.avi

abrazo

**Comment by mkreyness** [comment]
Siempre estamos hablando de que la base master (y todas las funciones de administracion sobre la misma) son WEB, en un hosting, no ?  Y la administracion local (de habilitar/deshabilitar gustos) la van a hacer desde una PC conectada al "server local" ? Esa info de cuales gustos hay deshabilitados/habilitados en cada local, tiene que llegar en algun momento a la central ? (por ej, para enterarse de que tienen que reponer ?).

**Comment by LeandroBraier** [comment]
1) Siempre estamos hablando de que la base master (y todas las funciones de
administracion sobre la misma) son WEB, en un hosting, no ? Y la
administracion local (de habilitar/deshabilitar gustos) la van a hacer
desde una PC conectada al "server local"? RESPUESTA: No quieren que sea una
página web. Tiene que ser un sistema que no dependa exclusivamente de
internet. Si se corta Internet debe funcionar igual.

2)  Esa info de cuales gustos hay deshabilitados/habilitados en cada local,
tiene que llegar en algun momento a la central ? (por ej, para enterarse de
que tienen que reponer ?). RESPUESTA: Si, debe llegar a la central. El
Administrador cuando entra al sistema debe poder ver qué se está
desplegando en cada pantalla.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 15:06 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Te separo y re-redacto las preguntas, porque parece que no se entendio lo que pregunté:

1.1) El hosting de la base maestra lo van a tener en un equipo privado propio de ellos en sus oficinas centrales o va a estar en Duplika ?

1.2) La instalacion que va en las heladerias, va a constar de 3 raspis, un server local y una PC o solo 3 raspis y una PC que ADEMAS va a hacer de server local ?

**Comment by LeandroBraier** [comment]
1.1) En Duplika u otro servidor mejor.

1.2) Eso no lo tengo claro. Lo consulto con MS si necesitás. Yo no termino
de entender cual sería la diferencia para ir pensando el sistema. Si lo
necesitás ahora consulta, sino andá avanzando y sumame las preguntas para
hacer después.

Fijate que te mandé un pedido para el Torneo que es Ultra prioridad. Hay
bugs a solucionar antes de lanzar.

**Comment by mkreyness** [comment]
Porque no me gustaria que la PC del tipo sea EL servidor del local, ya que cualquier macana que se mande usandola para otros fines (escuchar musica o boludear) puede poner en riesgo la operatoria de las raspis, la comunicacion con la central, etc.
Yo pondria 4 raspis por local, una de mas potencia (hoy en dia existe la Raspi 2 que tiene el doble de memoria y 6 veces la velocidad de las otras) y raspis B comunes en los televisores. De esa forma nuestro sistema SOLO se accede via "web local", pero no tocan "el servidor" para nada.

**Comment by LeandroBraier** [comment]
Dale. Pensemoslo asi me parece bien.

**Comment by mkreyness** [comment]
Otro tema es que estas heladerias estan en CHUBUT, obvio que si hay cualquier problema yo solo puedo dar asistencia remota, ya esta claro quien/como va a hacer la instalacion fisica y pruebas en Chubut ? Me parece que eso va a generar como minimo un kilombete de horas adicionales para la puesta a punto.

**Comment by LeandroBraier** [comment]
No te preocupes por eso. Hay sucursales en todo el país. Haríamos la prueba
en la sucursal de Palermo de última y después ellos se encargan de llevar
al resto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 18:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ah, en la pagina de ellos no decia que hubiera en Capital. Solo muestran de Chubut.

**Comment by LeandroBraier** [comment]
MK, te envié el CMS que te mostré el otro día por mail para que ya lo tengas. 

Eze está comprando los equipos para que empecemos a armar el sistema. Por otro lado voy armando los videos, cualquier cosa que necesites mientras tanto avisame.

abrazo

**Comment by mkreyness** [comment]
Bajé el CMS en el server de Benteveo, pero hay que instalar una base de datos y me encuentro con la sorpresa de que el mysql esta apagado o caido. Le podras mandar un mail a los de Duplika por la cuenta benteveo, diciendo que el mysql esta caido ?

**Comment by LeandroBraier** [comment]
Ahi escribí.

Qué raro que el Monitor.Us no me avisó nada de eso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-26 23:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
monitorea el port de mysql ?

**Comment by LeandroBraier** [comment]
Ni idea, si se puede hacer lo haría. Se ve que no jeje

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día MK!

Tengo el honor de presentarte los videos para que empieces a armar el sistema. Acá tenés las piezas por separado:

https://www.wetransfer.com/downloads/c7ee8b6560ecae506018ff137e0baf0620150905015156/8d1c6ca32214b46b4610156d15dc66ee20150905015156/94bb21

Acá tenés como quedaría todo armado, por las dudas de referencia:

https://www.wetransfer.com/downloads/f063ee74b23ce1854bc9fa47d416f89c20150904171750/87a7c4d0b36782bf2f436cbf5d5e924820150904171750/8685b2

Cualquier duda o cambio que necesites avisame, pero arranquemos ya con la programación del sistema.

Gracias!

abrazo

**Comment by mkreyness** [comment]
Dudas HARDWARE / RED: 
1) Entiendo que quedamos en que va a ir una PC machaza como armadora de contenidos que se distribuyen a las raspis, comandada (cuando se pueda, si no sigue activo lo que hubiere) desde un sitio web.
Convendria tener una dedicada lo antes posible para poder armar ahi (supongo que una maquina con un linux, la que se compró para Danica hubiera sido ideal pero creo que MS la reusó para otra cosa).
2) se compraron una o mas raspis ? Yo puedo ir usando la que tengo de Siguit pero ya es vieja y convendria ir teniendo una de las nuevas, que es lo que realmente se va a usar.

**Comment by mkreyness** [comment]
Otra cosa: el video final lo armaron con el ffmpeg ? Tendrias la linea de comandos o script con que lo armaron ?
Ya se que en este thread esta lo que hizo MS, pero no corresponde a ESTE video, no se si aplica o hay otro tipo de efectos.

**Comment by LeandroBraier** [comment]
MS: Lo que decís de raspis y demás lo hablamos con Eze y MS el lunes.

Respecto del video lo hicimos nosotros, sin ffmpeg ni nada. AHí tenés todos los videos sueltos para que los armes con el ffmpeg. El que está todo junto simplemente es para mostrarte como debería quedar final.

abrazo

**Comment by mkreyness** [comment]
Ok, el ffmpeg es la herramienta, pero para saber QUE hacer con la herramienta necesito instrucciones (el script de edicion o como se llame, tene en cuenta que yo hago software, nunca edite un video en mi vida). 

Es como que me dieras una docena de huevos, leche y azucar y me dijeras "haceme una torta de bodas como esta". Necesito minimamente una receta que me diga el orden y tiempos en que incorporar cada cosa. Mirando la torta no me doy la menor idea de eso.

Lo que yo armaria es un mecanismo por el cual, alguien que sepa (llamemoslo editor, no se si es el nombre correcto), pondria los parametros para que se genere la secuencia, pero qué valores poner (posicion en pantalla y tiempo de inicio de cada videito) los tiene que definir el editor.

Por ejemplo, con el video ddl640.avi, repetido 12 veces como input, MS, aplicando los comandos del ffmpeg antes mencionados, obtuvo el resultado output.avi. Ok.
Pero es solo un ejemplo de como usar el fmmpeg, no me dice nada respecto del orden, los tiempos y posiciones necesarias para ESTOS elementos que me mandaste.

**Comment by LeandroBraier** [comment]
MK, descargaste y viste los dos links que te pasé?

Acá tenés las piezas por separado:

https://www.wetransfer.com/downloads/c7ee8b6560ecae506018ff137e0baf0620150905015156/8d1c6ca32214b46b4610156d15dc66ee20150905015156/94bb21

Acá tenés como quedaría todo armado, por las dudas de referencia:

https://www.wetransfer.com/downloads/f063ee74b23ce1854bc9fa47d416f89c20150904171750/87a7c4d0b36782bf2f436cbf5d5e924820150904171750/8685b2

En función del segundo link tenés que programar en ffmpeg el primero. Ni el editor ni yo tenemos ni idea de ffmpeg.

**Comment by mkreyness** [comment]
Si, baje todo, y como te dije, no tengo la menor idea de como obtener el resultado a partir de las partes.
ffmpeg no es un lenguaje de programacion, es solo un utilitario que pega un video detras del otro.
Pero yo entiendo que no es eso lo que hay que hacer, porque hay transparencias y posiciones de las cosas que no se como se logran. En el ejemplo de MS hay claramente asignaciones de posiciones que yo no se que ponerles a estos.
Me refiero a cosas como esta que te copio abajo. Te aseguro que NO ES un programa esto, es una lista de relaciones de posiciones X Y en la pantalla para los sucesivos segmentos a concatenar, pero yo no tengo como adivinar cada videito en que posicion o en que momento lo tengo que poner.
Quien sea que lo haya editado tiene que saber que hizo, yo no lo puedo deducir de los materiales.
Como se los valores de X e Y para cada uno de los videitos que me pasaste y en que orden van ?

[base][A1] overlay=shortest=1 [tmp1];
[tmp1][B1] overlay=shortest=1:x=640 [tmp2];
[tmp2][A2] overlay=shortest=1:y=120 [tmp3];
[tmp3][B2] overlay=shortest=1:x=640:y=120 [tmp4];
[tmp4][A3] overlay=shortest=1:x=0:y=240 [tmp5];
[tmp5][B3] overlay=shortest=1:x=640:y=240 [tmp6];
[tmp6][A4] overlay=shortest=1:x=0:y=360 [tmp7];
[tmp7][B4] overlay=shortest=1:x=640:y=360 [tmp8];
[tmp8][A5] overlay=shortest=1:x=0:y=480 [tmp9];
[tmp9][B5] overlay=shortest=1:x=640:y=480 [tmp10];
[tmp10][A6] overlay=shortest=1:x=0:y=600 [tmp11];
[tmp11][B6] overlay=shortest=1:x=640:y=600

**Comment by LeandroBraier** [comment]
A partir del video completo.

Sino armame un instructivo de cómo necesitás que te pasemos los datos y lo
armamos. Pero necesito entenderlo primero.

Aunque insisto: creo que teniendo el video podés armar los coordenadas X e
Y en que van.

Transparencias y demás no hay. Los gustos van directamente sobre el video
de atrás. Si no se puede hacer eso te armo una versión en la que la parte
de abajo directamente esté vacía. Decime vos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 16:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Yo en el sistema lo que pienso tener son esos datos que figuran ahi en la secuencia, lo unico que va variar de un caso a otro son los nombres de los archivos de input, pero ENTIENDO que tendria que tener un campo por cada uno de esos parametros que estan ahi en eso que se llama "filter complex" (ni idea que significa eso), o sea una secuencia de nombres de archivo y para c/u de ellos estos atributos:

overlay
x
y

Entonces, vos me pasaste la lista de archivos, pero no se que poner en "overlay", "x" e "y".

**Comment by LeandroBraier** [comment]
La verdad sigo sin entender Marce. No me resulta instructivo lo que me
decís.

Overlay: Los 12 archivos más chicos de gustos van encima del archivo que
dice "Crema" y "Frutas". No sé como se traduce eso al código y al label:
"overlay"

X e Y de cada uno de esos 12 archivos lo podés calcular en base al archivo
que te pasé ya armado.

Lo que tenés que resolver desde la programación son eventos como: se acaba
el gusta 3, por lo cual ese video desaparece, pero no debe quedar el hueco.
El gusto 4 se ubica en el del 3, el gusto 5 se ubica en del 4 y el gusto 6
se ubica en el del 5.

Intuitivamente es todo lo que te puedo ayudar. Si me explicás cómo traduzco
esto al código que me pasaste lo hago.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 16:29 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Recapitulemos.
Lo que yo puedo hacer, y entendi que debo hacer, es un CMS en el cual un usuario DEFINE una SECUENCIA de videos de input para componer, con ciertos parametros que definan si cada paso REEMPLAZA o se SUPERPONE con el anterior, y en tal caso, en que posicion.
Con ese input yo voy a armar un string que se le pasa al FFMPEG para que genere el output.
En el CMS vas a tener (vos o quien sea que lo haga) que cargar o poner el URL de cada videito con esos parametros (overlay ? Si/No, posicion X y posicion Y de este video respecto del anterior) y el gusto al que esta asociado (asi puedo SALTEARME ese paso en caso de que el gusto no este.

Vos me estas dando los materiales, ok, pero cuándo tiene que entrar cada parte y donde tiene que mostrarse, no lo se.

**Comment by mkreyness** [comment]
Lean me podras remandar los videos de los supuestos gustos y el de base en otro formato que no sea .mov ?
Obviamente con el ffmpeg me funcionaron bien, pero cuando quiero ponerlos en el CMS como HTML5 no soporta formato .mov, no se ven y desluce todo para una presentacion.  
Los soportados por HTML5 son MP4, ogg y WebM. Obviamente me inclino por mp4.

Respecto a los tamaños, el resultado .mov que te dije que pesaba 9mb no era asi, pesa nada mas que 2.9 Mb (o sea, no llega a 3 Mb).
Es raro porque el de base original pesa como 54 Mb, supongo que debe estar uncompressed y el ffmpeg grabara todo compressed.

**Comment by LeandroBraier** [comment]
Si, Mk, no hay problema. Los pido. Me dirías qué codec de MP4 soporta o
cual preferís al menos? Me refiero a H.264 (el que usa YouTube) o AVCHD,
etc.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-14 18:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Eso ya depende de cada browser, pero supongo que todos soportan seguro el de youtube.
Para el ffmpeg ya ahora estamos encodeando H.264.

**Comment by LeandroBraier** [comment]
Ok, hoy lo pido MK!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-14 21:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
MK, te lo paso. Decime si es como lo necesitabas:

https://www.wetransfer.com/downloads/036438be79270d0b0be19337a3e2754c20150922194614/e0dd329aac5f087b664099f92c163b0220150922194614/43ab6a

**Comment by mkreyness** [comment]
Si, hay un par que estan repetidos ("frambuesa a la crema" y "frutilla crema") con lo que en realidad hay 22 y no 24.
Una cosa que me doy cuenta es que es mucho mas util ponerle a cada archivo el nombre del gusto que contiene (en un formato safe) porque asi es mas simple para subirlo al CMS. Estos ya los renombre, digo para cuando hagan el resto y/o arreglen esos 2 duplicados.

**Comment by LeandroBraier** [comment]
Gracias MK!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-22 22:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen lunes @mkreyness ! Cómo andás?

Consulta: Demo del sistema Del Viento para el miércoles. Si o no? Posible o imposible?

**Comment by mkreyness** [comment]
Estoy contrarreloj con las cosas de Academia.
PEro mas que nada es imposible, porque todavia no me dieron una maquina linux donde correr el ffmpeg y el sistema de distribucion en general (cosa que vengo diciendo desde el primer dia).
NO se puede hacer en los hostings que tenemos. Por muy linda que sea la raspi2, solo puede mostrar un video ya armado fijo.

**Comment by LeandroBraier** [comment]
Entendido MK. Le aviso a Marce.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-28 16:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness te paso el fondo modificado y 12 gustos para probar en cualquier orden.

Probalo. Si con esto lo solucionamos te los mando a todos con esta misma corrección.

http://we.tl/rER802lv2L

abrazo

**Comment by mkreyness** [comment]
ok, en un rato te digo y mando resultado.

**Comment by mkreyness** [comment]
lo que no entiendo por que ocupan tanto los pedacitos. 
Fijate que el que yo te mande armado completo, pesa lo mismo o menos que cualquiera de sus 12 pedacitos...

**Comment by mkreyness** [comment]
Ah pero me los mandaste en .mov.
Puedo armarlos igual con el ffmpeg, pero no los puedo ver con el CMS ojo, igual me los vas a tener que volver a mandar en .mp4, incluyendo la base.

**Comment by mkreyness** [comment]
Tambien, siempre para beneficio de Ezequiel (para evitar facturarle horas mias por estas cosas), cuando le pongan los nombres a los archivos que ya sean URL-safe, como todos los que cargamos en CMSs, sin blancos, sin letras acentuadas, y para poder yo copiar y pegar mas rapido, sin nada que no sea  exactamente el nombre del gusto.
Por ejemplo, si el gusto es "Dulce de Leche con Limón", el archivo se tiene que llamar Dulce-de-Leche-con-Limon.mp4, no "dulce de leche con limónHeladerias del Viento gusto 37.mp4"

**Comment by mkreyness** [comment]
Anyways, no recomiendo el Dulce de Leche con Limón.

**Comment by mkreyness** [comment]
Ahi te estoy mandando por wetransfer el resultado.
Yo sigo viendo que los gustos no completan el ancho, con lo que queda una parte "rara" entre el final de los gustos izquierdos y el principio de los derechos, y otra entre el final de los derechos y el ancho de la pantalla.

**Comment by LeandroBraier** [comment]
Entiendo MK. NO te preocupes. La tanda que viene ya va a venir con los
nombres así, disculpá.+

Ahi le mandé la prueba al realizador así vemos cómo l resolvemos.

No hay posibilidad de que el ffmpeg esté escalando las piezas de los gustos
no?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-24 14:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No, yo lo unico que le pongo es la coordenada superior izquierda
donde mostrarlo, como es 1280 mando los izquierdos a la posicion 0,
y los derechos a la posicion 640, nunca le digo cuanto tienen que
ocupar.

El 24/10/2015 a las 17:31,
  LeandroBraier escribió:

Entiendo MK. NO te preocupes. La tanda que viene ya va
  a venir con los
  nombres así, disculpá.+

  Ahi le mandé la prueba al realizador así vemos cómo l resolvemos.

  No hay posibilidad de que el ffmpeg esté escalando las piezas de
  los gustos
  no?

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-24 14:47 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Ahi te estoy mandando por wetransfer el resultado.
  > Yo sigo viendo que los gustos no completan el ancho, con lo
  que queda una
  > parte "rara" entre el final de los gustos izquierdos y el
  principio de los
  > derechos, y otra entre el final de los derechos y el ancho de
  la pantalla.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/DELVIENTO/issues/1#issuecomment-150836954
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Te paso acá las coordenadas que está usando el editor para armar los gustos. Fijate si acomodando estas coordenadas con la última versión que te mandé ahora queda bien.

Columna izquierda en la posición 45,8 

Columna derecha en la posición 683,8.

Sino se puede avisame y le pido que adapte los videos a estas coordenadas. Elt ema es que eso puede llevar varias horas de export.

abrazo

**Comment by mkreyness** [comment]
Estamos hablando de pixeles, que es 0.8 de pixel ? Eso seguro que no.
Esto seria para centrarlos ? Pero van a quedar espacios sin cubrir a izquierda y derecha en ambos lados, yo no se si eso esta bien, es lo que el cliente quiere ? A mi me da igual

**Comment by mkreyness** [comment]
puedo probar 46 y 684

**Comment by LeandroBraier** [comment]
Probalo a ver si eso mejora o nos demuestra cuál es el error que estamos
cometiendo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Recibido MK! Sigue habiendo diferencia de color. Eso me intriga mucho, no sé qué puede ser.

Te paso acá los gustos en 640px de ancho a ver si eso ayuda

https://www.wetransfer.com/downloads/2a26cf4d6f9ed4b3f4c6cf7ddd2f7db020151026141312/3a801c3fa0bc8fd407f1f97706baeed720151026141312/4c2a1f

Probalos porfa.

**Comment by LeandroBraier** [comment]
@mkreyness estamos regenerando los videos en base a cambios pedidos por el cliente en la reunión de la semana pasada.

Pregunta 1: Esto lo vamos a poder actualizar online para que lo vean en Neuquén, no hace falta que esté dentro de la raspie cuando hagan el envío no?

Pedido 2: Mientras no haya una promoción para el intervalo, vamos a utilizar el intervalo del comienzo de 15 segundos de duración en su lugar. Quedaría así la secuencia: PLACA LOGO DEL VIENTO 15 SEGUNDOS / VIDEO DE GUSTOS 1 MIN / PLACA LOGO DEL VIENTO 15 SEGUNDOS / VIDEO DE GUSTOS 1 MIN

Pedido 3: El cliente pidió que en las 3 pantallas se vean colores de fondo distintos. Si te damos los 3 videos, vos podés dejarlo seteado así? Para eso los gustos tendrían que tener fondo TOTALMENTE transparente y eso es lo que vamos a buscar.

abrazo

**Comment by mkreyness** [comment]
1) claro, la idea es que todo se sube al sitio web (que por ahora esta en benteveo.tv) y cada maquina se ocupa de levantarlo como pueda, regenerar los videos y mandarlos a las raspis.

2) esto tengo que implementarlo todavia, pero seria parte de lo que se arma en la secuencia.

3) Claro, cada secuencia puede tener un FONDO diferente, y si los gustos son transparentes es ideal.

PERO acordate que el fondo tambien se compone de varias partes, una por cada CATEGORIA, mas el logo animado central, todo eso se tiene que componer al momento de armar yo la secuencia, tengan en cuenta entonces armar todas esas cosas por separado y ver que pasa cuando se superponen con cada posible color de fondo.

**Comment by LeandroBraier** [comment]
1) Perfecto!

2) Genial.

3) Lo tengo en cuenta y ya lo pedí de esa manera. El video de fondo en 4
partes (2 superiores y 2 inferiores) y el logo aparte con transparencia. De
esos videos tendrías 3, uno por cada pantalla y color.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-02 9:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No entiendo por que dos abajo, no es igual izquierda y derecha abajo ?

**Comment by LeandroBraier** [comment]
Teóricamente si, pero pensé que te era más fácil así. Ya lo pedí así, te
jode? Sino lo cambio.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
No me jode, pero seguro que combina bien el movimiento de la guardita de abajo al ser en 2 partes ?

**Comment by LeandroBraier** [comment]
Tenés razón, lo pido distinto entocnes.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
MK, cómo venimos con esto? Hoy me preguntó MS en la produ.

**Comment by mkreyness** [comment]
estoy igual que el viernes, no empece todavia a armar los nuevos videos en base al nuevo material.

**Comment by LeandroBraier** [comment]
Ah, ok. Mañana metamosle a eso entonces, podés? Porque seguro MS va a
empezar reclamar. Cualquier cosa que necesites avisame.

abrazo y que descanses!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, si puedo ir avanzando algo hoy tambien, lo que pasa es que al final estuve mucho con las cosas de  Klaukol como siempre

**Comment by LeandroBraier** [comment]
Si, no te preocupes. Solo tanteaba para avanzar, te entiendo. Todo bien.

abrazo y buenas noches!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 21:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
La noche es joven !

**Comment by LeandroBraier** [comment]
@mkreyness necesitamos en algún momento (podría ser el viernes o la semana que viene) que @valentinsabbath tomen control de este sistema y empezar a monitorearlo. Qué necesitamos para esto?

**Comment by mkreyness** [comment]
Tengo que explicarle como funciona, y ademas todavia yo tengo una maquina.
Hay UNA instalacion (Polonia) que nunca logre conectarme remoto para terminar de instalar.
Le voy escribiendo un mail explicando lo que me acuerdo y pasando los links de las cosas.

**Comment by LeandroBraier** [comment]
Dale, perfecto. Estoy con Valentin en la produ y le estoy avisando.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-20 16:56 GMT-03:00 mkreyness notifications@github.com:
