### ISSUE TITLE
Bug de Fuente y GPU

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DELVIENTO#2]
@mkreyness y @valentinsabbath : el cliente respondió a mi informe que lo mismo le ocurre en todas las sucursales y no puede cambiar la instalación eléctrica en todas, por lo cual me pide una solución alternativa.

Estuve investigando y pensando un poco y llegué a la siguiente conclusión:

1) Para el tema fuentes que se queman: ya estamos testeando las fuentes Sony. Si esas no se queman ya está resuelto, cambiamos por esas fuentes. Esta es la data que encontré en una web y que nos puede servir de referencia:

**La alimentación de la Raspberry Pi es importante. Necesitaremos un cargador de móvil o similar con conexión micro usb y que suministre más de 750 mA de corriente. Mejor si nos vamos a una fuente de alimentación que dé más de un amperio, ya que hay muchos usuarios que se han vuelto prácticamente locos con sus Raspberry Pi por elegir una fuente de alimentación que no daba la suficiente corriente y han experimentado todo tipo de fallos. Así que, si teníais pensado utilizar el cargador de vuestro móvil, aseguraos de la corriente suministrada por el mismo. De todas formas, un cargador no supone un desembolso grande y siempre viene bien por si acaso perdemos el del móvil.**
Fuente: http://www.xatakahome.com/domotica/algunas-cosas-a-tener-en-cuenta-antes-de-usar-una-raspberry-pi

2) Para el tema GPU que se cuelga encontré un posible upgrade para el sistema (que quizá sí habría que cotizarle al cliente) que es una especie de placa de video externa o prolongador que refuerce la placa de video de la Raspi. Tengan en cuenta que no soy ningún experto, así que puede que le está errando fierísimo pero es una idea nomás, que seguro uds pueden superar ampliamente:

http://articulo.mercadolibre.com.ar/MLA-609490326-adaptador-placa-de-de-video-externa-usb-30-a-hdmi-full-hd-_JM

Diganme qué opinan, si estoy sobre el buen camino o no entiendo nada. En función de esto quiero poder proponerle a Eze el upgrade para el sistema para evitar estos problemas de inestabilidad más allá de la instalación eléctrica.

abrazo

**Comment by mkreyness** [comment]
No Lean, ese prolongador no ayuda en nada, es solo un conversor electirco de USB a HDMI, para el que no tiene una salida HDMI en su hardware.  Muy por el contrario, requiere un driver, que es el que en realidad hace todo, y solo funciona en Windows.

**Comment by LeandroBraier** [comment]
Entiendo, vale la intención entonces jeje.

Te paso repropuesta que me dio @valentinsabbath por teléfono recién:

**SOLUCIÓN DEFINITIVA**
Estabilizador + batería de emergencia para que, si hay baja de tensión o corte de luz, se apaguen bien las raspis y no se corrompan las tarjetas. Más allá de eso, para lo del GPU mantenemos el reseteo automático cada tanto. 

Ahi estaría OK?

**Comment by mkreyness** [comment]
No se como hariamos lo de que "se apaguen bien", la raspi tendria que poder sensar el nivel de bateria.
Yo de esas cosas no entiendo mucho, pero todas las UPS que he visto llevan un driver que corre permanentemente en la PC y que se comunica con la parte de hibernacion/suspension del Windows. Dudo que haya algo asi preparado para raspis, habria que investigar, y aun asi, es una relacion uno a uno entre la UPS y UNA pc, aunque haya conectadas varias. Nunca vi que se le avise a TODOS los equipos conectados. Igual eso si lo podriamos coordinar que se apaguen todas si le llega la señal a una.

**Comment by LeandroBraier** [comment]
@valentinsabbath tendría que responderte eso cuando pueda.

**Comment by ghost** [comment]
Cuando llego a casa les paso el posteo que quizás ayude

**Comment by ghost** [comment]
Por un lado, esta es la fuente oficial de Adafruit, que ofrece 5.2 V para evitar bajo voltaje en la salida.
https://www.adafruit.com/products/2297

Y la posible solución:
 The UPS PIco will automatically shut-down your Raspberry Pi if there is a power failure, and can be set to automatically monitor and reboot your Pi once power has been restored!
https://www.modmypi.com/raspberry-pi/breakout-boards/pi-modules/ups-pico

**Comment by LeandroBraier** [comment]
Muy buenos datos Valen!! Cada una de esas fuentes vale como 800 pesos no? Y el tema es donde se consiguen.

**Comment by ghost** [comment]
El UPS sale 27 libras (no se cuánto sale el transporte). 
Lo que dice Ezequiel es que se puede importar a Chile
http://www.pimodulescart.com/shop/item.aspx?itemid=5

**Comment by LeandroBraier** [comment]
Buenisimo entonces! Igual son por lo menos 600 pesos no? Eze te dijo que
era posible?

**Comment by ghost** [comment]
No pude comentarle muy profundamente el tema porque no sabía cuánto salia
el módulo.
Tengo otra idea alternativa y mas fácil de lograr: comprar un ups, con el
alimentar el server y las raspis, cuando se corte la luz, el server recibe
la señal del ups, envia señal de apagado a las raspis y el server también
se apaga. Con eso conseguimos un apagado seguro y un circuito estabilizado

**Comment by mkreyness** [comment]
Mientras la UPS tenga un driver que corra en Debian, y se le puedan programar acciones, estaria barbaro.

**Comment by ghost** [comment]
Comparto por aca el listado de ups compatibles con "nut" el driver ups para
Linux.
http://networkupstools.org/stable-hcl.html
El 25 jul. 2016 10:24 p. m., "mkreyness" notifications@github.com
escribió:

Mientras la UPS tenga un driver que corra en Debian, y se le puedan
programar acciones, estaria barbaro.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/LeandroBraier/DELVIENTO/issues/2#issuecomment-235135847,
or mute the thread

**Comment by mkreyness** [comment]
de esas la unica que estoy seguro que existe aca es APC. Yo tuve alguna gamatronic (muy entry level) pero creo que era malisima.
Esta es la tienda oficial de APC en ML:
http://computacion.mercadolibre.com.ar/ups/apc-ups_Tienda_apc-soluciones
no estoy seguro de que algun modelo coincida con la lista, porque todos los nombres tienen alguna variante adicional.

**Comment by ghost** [comment]
Un UPS Linux compatible y fácil de conseguir:
http://articulo.mercadolibre.com.ar/MLA-615507284-ups-apc-bx1100ci-1100va-back-ups-6-tomas-estabilizador-_JM
Y su howto:
http://www.cyberciti.biz/faq/debian-ubuntu-centos-rhel-install-apcups/
Creo que con esto lo solucionamos

**Comment by ghost** [comment]
Me ganaste por 9 segundos :D

**Comment by ghost** [comment]
@LeandroBraier @mkreyness  si dan el ok con el ups, ya le podríamos preguntar a Ezquiel si aprueba el plan y tratar de solucionar el problema electrico. 
 De paso informo que el domingo se rompió el sistema de la cartelera de Palermo que está en el medio

**Comment by mkreyness** [comment]
No hay una de menor potencia mas barata ? Es mucho 1000va para una PC y 3 raspis. Con una de 800 alcanza y sobra.
Palermo: la del medio fue la que le cambiaste la fuente, no Lean ? Y era la tarjeta nueva.

**Comment by ghost** [comment]
Es una PC, 3 raspis y el router (para que pueda enviar la señal de apagado a través de la red)

**Comment by ghost** [comment]
Serían 5 tomas

**Comment by mkreyness** [comment]
pero lo que consume todo lo que no tiene motores es infimo. Lo unico con carga importante es la fuente de la PC. Si por ejemplo tiene una fuente de 500w, esto le daria potencia para mas de 2 horas, no tiene sentido.

**Comment by ghost** [comment]
Uno asi, 350va y tiene comunicación usb. Tiene 3 tomas por lo que enchufamos SOLO las raspis con zapatilla  al ups. Está terminantemente prohibido enchufar zapatillas a un aparato de estos, pero con el consumo de las raspis no creo que se rompa  nada. 
http://articulo.mercadolibre.com.ar/MLA-614361704-ups-apc-back-bk350ei-350va-ideal-hogar-estabilizador-xtr-_JM

**Comment by mkreyness** [comment]
me parece suficiente y un costo mas apropiado.

**Comment by LeandroBraier** [comment]
Buenisimo chicos! Gran trabajo! Al mediodía consulto con Eze y les confirmo.

abrazo
